In [374]:
import pandas as pd

df = pd.read_excel('Table_1.2_Primary_Energy_Production_by_Source.xlsx', sheetname='Monthly Data', header=None)

In [375]:
df = df.drop(df.iloc[:,0:10])

In [376]:
df = df.drop([11])

In [377]:
df = df.drop(columns = range(1,9))

In [378]:
df = df.drop(columns = range(11,14))

In [379]:
df.columns = df.iloc[0]

In [380]:
df = df.drop(10)

In [381]:
not_num = pd.to_numeric(df['Solar Energy Production'], errors='coerce')

In [382]:
df['Solar Energy Production'] = not_num

In [383]:
df = df.dropna()

In [384]:
df = df.reset_index(drop = True)

In [385]:
df['Month'] = pd.to_datetime(df['Month']).dt.date

In [386]:
df['Total Solar and Wind Production (Quadrillion Btu)'] = (df['Solar Energy Production'] + df['Wind Energy Production'])

In [387]:
data = df

In [388]:
data

10,Month,Solar Energy Production,Wind Energy Production,Total Solar and Wind Production (Quadrillion Btu)
0,1984-01-01,-0.000001,0,-1e-06
1,1984-02-01,0.000001,2e-06,3e-06
2,1984-03-01,0.000002,2e-06,4e-06
3,1984-04-01,0.000003,6e-06,9e-06
4,1984-05-01,0.000007,8e-06,1.5e-05
5,1984-06-01,0.000010,6e-06,1.6e-05
6,1984-07-01,0.000003,5e-06,8e-06
7,1984-08-01,0.000009,3e-06,1.2e-05
8,1984-09-01,0.000010,5e-06,1.5e-05
9,1984-10-01,0.000007,9e-06,1.6e-05
10,1984-11-01,0.000004,9e-06,1.3e-05
11,1984-12-01,0.000000,1.3e-05,1.3e-05
12,1985-01-01,0.000005,7e-06,1.2e-05
13,1985-02-01,-0.000001,1.1e-05,1e-05
14,1985-03-01,0.000001,7e-06,8e-06
15,1985-04-01,0.000013,6e-06,1.9e-05
16,1985-05-01,0.000015,4e-06,1.9e-05
17,1985-06-01,0.000016,4e-06,2e-05
18,1985-07-01,0.000011,1e-06,1.2e-05
19,1985-08-01,0.000021,4e-06,2.5e-05
20,1985-09-01,0.000014,9e-06,2.3e-05
21,1985-10-01,0.000010,5e-06,1.5e-05
22,1985-11-01,0.000003,2e-06,5e-06
23,1985-12-01,0.000002,1e-06,3e-06
24,1986-01-01,0.000007,2e-06,9e-06
25,1986-02-01,0.000006,2e-06,8e-06
26,1986-03-01,0.000011,7e-06,1.8e-05
27,1986-04-01,0.000014,6e-06,2e-05
28,1986-05-01,0.000019,8e-06,2.7e-05
29,1986-06-01,0.000015,5e-06,2e-05
...,...,...,...,...
396,2017-01-01,0.033557,0.182789,0.216346
397,2017-02-01,0.040038,0.195296,0.235334
398,2017-03-01,0.062625,0.23026,0.292885
399,2017-04-01,0.069427,0.226762,0.296189
400,2017-05-01,0.081055,0.206832,0.287887
401,2017-06-01,0.086535,0.182501,0.269036
402,2017-07-01,0.083455,0.147044,0.230499
403,2017-08-01,0.079621,0.125491,0.205112
404,2017-09-01,0.073652,0.1645,0.238152
405,2017-10-01,0.068139,0.233141,0.30128
406,2017-11-01,0.050016,0.221863,0.271879
407,2017-12-01,0.048769,0.226411,0.27518
408,2018-01-01,0.049852,0.247478,0.29733
409,2018-02-01,0.058036,0.221994,0.28003
410,2018-03-01,0.075685,0.25136,0.327045
411,2018-04-01,0.088844,0.246749,0.335593
412,2018-05-01,0.099541,0.217452,0.316993
413,2018-06-01,0.106872,0.224581,0.331453
414,2018-07-01,0.099898,0.147533,0.247431
415,2018-08-01,0.098816,0.179934,0.27875
416,2018-09-01,0.090243,0.165619,0.255862
417,2018-10-01,0.075563,0.194826,0.270389
418,2018-11-01,0.058352,0.206896,0.265248
419,2018-12-01,0.049650,0.22871,0.27836
420,2019-01-01,0.055076,0.231841,0.286917
421,2019-02-01,0.059171,0.212329,0.2715
422,2019-03-01,0.088184,0.239868,0.328052
423,2019-04-01,0.100566,0.278391,0.378957
424,2019-05-01,0.106854,0.243909,0.350763
425,2019-06-01,0.115995,0.215581,0.331576

In [390]:
indicator = ['2005-08', '2007-12', '2009-02']

In [391]:
print(indicator[1])

2007-12

In [392]:
indicator = pd.to_datetime(indicator).date

In [393]:
print(indicator[0])

2005-08-01